# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSDemo
  pod 'ExtoleMobileSDK', '>= 0.0.94'

  target 'iOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoUITests' do
    # Pods for testing
  end

end
